/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cricbuzz;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        System.out.println("****************************************");
    }
}

